### ISSUE TITLE
Errors when saving BCFNT fonts

### ISSUE THREAD

**Issue by Century-300** [TheFearsomeDzeraora/NintyFont#4]
Hey there!
Sorry for bothering, but I found an issue when making edits to a BCFNT font from Persona Q2.
While the tool can preview the font file and glyph data just fine, the image itself seems to not be saved properly, when reopened in the tool it looks like this.

![image](https://user-images.githubusercontent.com/74802102/156216408-358e3bfd-0897-454f-a0a6-8c1a57c9285d.png)

This isn't just an error with the preview or anything either, it shows up like this in-game aswell.

![image](https://user-images.githubusercontent.com/74802102/156216561-17ad300f-5b7f-496e-b0b7-a21b6624e02a.png)

I'm not sure of what could be causing the issue, so I wanted to bring this bug to your attention.
I'm also attaching the font files from the game if you want to look deeper into this problem.
[font.zip](https://github.com/TheFearsomeDzeraora/NintyFont/files/8163532/font.zip)

**Comment by hadashisora** [comment]
Hi! Thanks for the report and sorry for the late reply. Looked into the matter today, apparently I made a very dumb mistake in the loops for encoding/decoding 3DS textures and then copy-pasted that all over the texture codec. I've updated the latest build (Alpha 2) with the fix and tested it with the files you provided, so please try it and hopefully it all works now.

**Comment by Century-300** [comment]
> Hi! Thanks for the report and sorry for the late reply. Looked into the matter today, apparently I made a very dumb mistake in the loops for encoding/decoding 3DS textures and then copy-pasted that all over the texture codec. I've updated the latest build (Alpha 2) with the fix and tested it with the files you provided, so please try it and hopefully it all works now.

Omg Thank you! Texture saving works just fine now!
